from tree import Tree

tree = Tree([1, 2, 4, 8, 16, 32, 64, 128, 256, 512])
tree.print_tree()
# print(tree.get_inorder(tree.root))
# tree.insert_value(tree.root, 15)
# tree.print_tree()
# tree.print_tree()
# print(tree.get_all_level_nodes(4))
# tree.print_tree()
# tree.find_and_delete(256)
# tree.print_tree()
# tree.find_and_delete(2)
# tree.print_tree()
print(tree.get_min())
print(tree.get_max())
print(tree.rebalance())